all:
	sudo mkdir -p /home/cogroid/local/libtool/x64
	cd ../../; \
	./configure --prefix=/home/cogroid/local/libtool/x64; \
	export CPPFLAGS="-v"; \
	export CFLAGS="-v"; \
	make

install:
	cd ../../; \
	sudo make install
