#!/bin/bash

sed -i 's/$(AM_V_CCLD)$(libltdl_libltdl_la_LINK) $(am_libltdl_libltdl_la_rpath) $(libltdl_libltdl_la_OBJECTS) $(libltdl_libltdl_la_LIBADD) $(LIBS)/arm\-linux\-androideabi\-gcc \-shared  \-fPIC \-DPIC  libltdl\/loaders\/.libs\/libltdl_libltdl_la\-preopen.o libltdl\/.libs\/libltdl_libltdl_la\-lt__alloc.o libltdl\/.libs\/libltdl_libltdl_la\-lt_dlloader.o libltdl\/.libs\/libltdl_libltdl_la\-lt_error.o libltdl\/.libs\/libltdl_libltdl_la\-ltdl.o libltdl\/.libs\/libltdl_libltdl_la\-slist.o libltdl\/.libs\/lt__argz.o libltdl\/.libs\/libltdlS.o  libltdl\/.libs\/libltdl.lax\/dlopen.a\/dlopen.o   -L\/home\/cogroid\/local\/android\-ndk\-r18b\/platforms\/android\-18\/arch\-arm\/usr\/lib -B\/home\/cogroid\/local\/android\-ndk\-r18b\/platforms\/android\-18\/arch\-arm\/usr\/lib \-L\/home\/cogroid\/local\/android\-ndk\-r18b\/toolchains\/arm\-linux\-androideabi\-4.9\/prebuilt\/linux\-x86_64\/lib\/gcc\/arm\-linux\-androideabi\/4.9.x\/armv7\-a\/thumb \-B\/home\/cogroid\/local\/android\-ndk\-r18b\/toolchains\/arm\-linux\-androideabi\-4.9\/prebuilt\/linux\-x86_64\/lib\/gcc\/arm\-linux\-androideabi\/4.9.x\/armv7\-a\/thumb \-g \-O2 \-march=armv7\-a \-\-sysroot \/home\/cogroid\/local\/android\-ndk\-r18b\/sysroot \-fstack\-protector\-strong \-O2 \-march=armv7\-a \-\-sysroot \/home\/cogroid\/local\/android\-ndk\-r18b\/sysroot \-fstack\-protector\-strong \-O2 \-march=armv7\-a \-\-sysroot \/home\/cogroid\/local\/android\-ndk\-r18b\/sysroot \-fstack\-protector\-strong \-O2   \-Wl,\-soname \-Wl,libltdl.so \-o libltdl\/.libs\/libltdl.so/g' ./Makefile

sed -i 's/--silent//g' ./Makefile
#sed -i 's/$(AM_V_CCLD)$(libltdl_libltdl_la_LINK) $(am_libltdl_libltdl_la_rpath) $(libltdl_libltdl_la_OBJECTS) $(libltdl_libltdl_la_LIBADD) $(LIBS)/echo "$(AM_V_CCLD)$(libltdl_libltdl_la_LINK) $(MYLDFLAGS) $(am_libltdl_libltdl_la_rpath) $(libltdl_libltdl_la_OBJECTS) $(libltdl_libltdl_la_LIBADD) $(LIBS)"\n\t$(AM_V_CCLD)$(libltdl_libltdl_la_LINK)  $(LDFLAGS) $(am_libltdl_libltdl_la_rpath) $(libltdl_libltdl_la_OBJECTS) $(libltdl_libltdl_la_LIBADD) $(LIBS)/g' ./Makefile
sed -i 's/#####/#LDLP#####\nLDFLAGS= -v --target=arm-linux-androideabi -march=armv7-a -fPIC -fno-integrated-as --sysroot \/home\/cogroid\/local\/android-ndk-r18b\/sysroot -isystem \/home\/cogroid\/local\/android-ndk-r18b\/sysroot\/usr\/include\/arm-linux-androideabi -D__ANDROID_API__=18 -fexceptions -frtti -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -I\/home\/cogroid\/local\/android-ndk-r18b\/sources\/cxx-stl\/llvm-libc++\/include -I\/home\/cogroid\/local\/android-ndk-r18b\/sources\/cxx-stl\/llvm-libc++abi\/include -I\/home\/cogroid\/local\/android-ndk-r18b\/sources\/android\/support\/include -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security -DNDEBUG -O2 -I\/usr\/include -L\/home\/cogroid\/local\/android-ndk-r18b\/platforms\/android-18\/arch-arm\/usr\/lib -B\/home\/cogroid\/local\/android-ndk-r18b\/platforms\/android-18\/arch-arm\/usr\/lib -L\/home\/cogroid\/local\/android-ndk-r18b\/toolchains\/arm-linux-androideabi-4.9\/prebuilt\/linux-x86_64\/lib\/gcc\/arm-linux-androideabi\/4.9.x\/armv7-a\/thumb -B\/home\/cogroid\/local\/android-ndk-r18b\/toolchains\/arm-linux-androideabi-4.9\/prebuilt\/linux-x86_64\/lib\/gcc\/arm-linux-androideabi\/4.9.x\/armv7-a\/thumb/g' ./Makefile
sed -i 's/#LDLP#####/#DTRP#####\nLD_LIBRARY_PATH=\/home\/cogroid\/local\/android-ndk-r18b\/platforms\/android-18\/arch-arm\/usr\/lib:\/home\/cogroid\/local\/android-ndk-r18b\/toolchains\/arm-linux-androideabi-4.9\/prebuilt\/linux-x86_64\/lib\/gcc\/arm-linux-androideabi\/4.9.x\/armv7-a\/thumb/g' ./Makefile
sed -i 's/#DTRP#####/DT_RPATH=\/home\/cogroid\/local\/android-ndk-r18b\/platforms\/android-18\/arch-arm\/usr\/lib:\/home\/cogroid\/local\/android-ndk-r18b\/toolchains\/arm-linux-androideabi-4.9\/prebuilt\/linux-x86_64\/lib\/gcc\/arm-linux-androideabi\/4.9.x\/armv7-a\/thumb/g' ./Makefile
